### ISSUE TITLE
Unable to start docker container

### ISSUE THREAD

**Issue by aarthisankaran** [awsdocs/aws-sam-developer-guide#38] opened 2020-01-22 05:03 UTC
Can you help with below error?

$ sam local start-api -d 3030 --template template.yaml --debugger-path ./ --debug-args "-delveAPI=2"  
Mounting LocalServer at http://127.0.0.1:3000/graphql [POST]
Mounting LocalServer at http://127.0.0.1:3000/health [GET]
You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. You only need to restart SAM CLI if you update your AWS SAM template
 * Tip: There are .env files present. Do "pip install python-dotenv" to use them.
2020-01-21 23:54:10  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)

Invoking .dev/localserver (go1.x)

Fetching lambci/lambda:go1.x Docker container image......
Mounting /Users/qgv313/development/qgv313org/GraphQL/securedcard-data-api as /var/task:ro,delegated inside runtime container
Could not create config directory: mkdir /home/sbx_user1051: permission denied.API server listening at: [::]:3030
.
.
.
2020-01-22T04:54:17Z info layer=debugger launching process with args: [/var/task/.dev/localserver]
could not launch process: fork/exec /var/task/.dev/localserver: no such file or directory

**Comment by mark-hirayama** [comment] 2020-01-24 16:27
This is a duplicate of an issue in the SAM CLI repo:    https://github.com/awslabs/aws-sam-cli/issues/1740

**Closed by mark-hirayama** 2020-01-24 16:27 UTC
